ds: 'uvd'
model_name: 'resnet'

# Training parameters
log_dir: './tests_uvd/'
train_dir: './data/uvd/train'
val_dir: './data/uvd/val'
input_width: 304
input_height: 228
output_width: 304
output_height: 228
init_weights: './data/weights/resnet_v2_50/resnet_v2_50.ckpt'
resume_weights: './tests_uvd/resnet50_2805/'
max_epochs: 40

# Optimizer parameters
learning_rate: 0.0001
beta1: 0.9
l2_reg_scale: 0.00001

# Testing parameters
checkpoint_dir: './tests_uvd/resnet50_2805/'
test_dir: './data/uvd/test'
